crates/mipsy_lib/src/inst/register.rs, crates/mipsy_lib/src/runtime/state.rs, crates/mipsy_lib/src/util.rs
=> add serializing and registers fn

crates/mipsy_web/_static/index.html, crates/mipsy_web/src/components/sourcecode.rs, crates/mipsy_web/src/lib.rs, crates/mipsy_web/src/pages/main/app.rs, crates/mipsy_web/src/pages/main/update.rs, crates/mipsy_web/static/index.html
just PR'ing this to wait till after the lecture
=> remove unneccessary source renders, fix unsaved semantics

crates/mipsy_web/README.md, crates/mipsy_web/src/worker.rs
Removes a magic number (and also improves docs for hot reload)
=> Remove magic number from mipsy_web worker

.github/workflows/build.yml, .github/workflows/test.yml
Build on Ubuntu, Mac, and Windows.
Only test on Ubuntu because of issues
=> better github workflows

Cargo.lock, crates/mipsy/src/main.rs, crates/mipsy_interactive/src/interactive/commands/load.rs, crates/mipsy_utils/Cargo.toml, crates/mipsy_utils/src/expand.rs, crates/mipsy_utils/src/lib.rs
=> add some filename niceties

Cargo.lock, crates/mipsy_lib/Cargo.toml, crates/mipsy_lib/src/compile/mod.rs, crates/mipsy_web/src/bin/worker.rs, crates/mipsy_web/src/components/decompiled.rs, crates/mipsy_web/src/components/navbar.rs, crates/mipsy_web/src/pages/main/app.rs, crates/mipsy_web/src/state/config.rs, crates/mipsy_web/src/state/state.rs, crates/mipsy_web/src/state/update.rs, crates/mipsy_web/src/worker.rs
`break` instruction now works correctly
edit: breakpoints via buttons also work as intended :)
fixes #155
=> Breakpoints

crates/mipsy_web/src/pages/main/app.rs
=> correctly add callback

crates/mipsy_codegen/src/lib.rs, crates/mipsy_instructions/src/base.rs, crates/mipsy_instructions/src/lib.rs, crates/mipsy_instructions/src/meta.rs, crates/mipsy_interactive/src/interactive/commands/breakpoint.rs, crates/mipsy_interactive/src/interactive/commands/breakpoints.rs, crates/mipsy_interactive/src/interactive/commands/load.rs, crates/mipsy_interactive/src/interactive/commands/print.rs, crates/mipsy_interactive/src/interactive/mod.rs, crates/mipsy_interactive/src/interactive/runtime_handler.rs, crates/mipsy_lib/src/compile/data.rs, crates/mipsy_lib/src/compile/extra.rs, crates/mipsy_lib/src/compile/mod.rs, crates/mipsy_lib/src/compile/text.rs, crates/mipsy_lib/src/decompile/mod.rs, crates/mipsy_lib/src/error/runtime/mod.rs, crates/mipsy_lib/src/inst/instruction.rs, crates/mipsy_lib/src/runtime/mod.rs, crates/mipsy_lib/src/runtime/state.rs, crates/mipsy_lib/src/util.rs, crates/mipsy_parser/src/directive.rs, crates/mipsy_parser/src/misc.rs, crates/mipsy_utils/src/expand.rs
Just went around the codebase and fixed up various nitpicks that clippy pointed out. Left mipsy_web alone because I don't know the codebase well enough to judge whether the suggested lints are correct or not (there's a lint that pops up in mipsy for example about a useless closure which i'm pretty sure is incorrect)
=> fix various clippy lints

crates/mipsy_web/src/worker.rs
I did this from my phone as m y itnernert died lmao
=> this should not be needed, and yet

crates/mipsy_interactive/src/interactive/commands/breakpoint.rs, crates/mipsy_interactive/src/interactive/commands/help.rs, crates/mipsy_interactive/src/interactive/commands/mod.rs, crates/mipsy_interactive/src/interactive/commands/watchpoint.rs, crates/mipsy_interactive/src/interactive/mod.rs, crates/mipsy_interactive/src/interactive/runtime_handler.rs, crates/mipsy_lib/src/inst/register.rs, crates/mipsy_lib/src/runtime/mod.rs
no support for associated commands or conditions for watchpoints included
fixes #46
=> add watchpoints

crates/mipsy_interactive/src/interactive/commands/breakpoint.rs, crates/mipsy_interactive/src/interactive/error.rs, crates/mipsy_interactive/src/interactive/mod.rs, crates/mipsy_lib/src/error/runtime/mod.rs
=> allow breakpoints based on line numbers

crates/mipsy_interactive/src/interactive/commands/labels.rs, crates/mipsy_interactive/src/interactive/mod.rs
=> use all watchpoints relevant to the current instruction

crates/mipsy_lib/src/error/runtime/mod.rs
=> use register values at time of uninitilization

crates/mipsy_web/src/state/state.rs, crates/mipsy_web/src/state/update.rs, crates/mipsy_web/src/worker.rs
to implement needed some way to tell frontend that we've already breaked for a particular breakpoint, else it would never progress
=> allow breakpoints after syscalls

crates/mipsy_web/src/components/registers.rs, crates/mipsy_web/src/components/settings_modal.rs, crates/mipsy_web/src/components/toggle.rs, crates/mipsy_web/src/state/config.rs
Welp, since I can't teach today thought I'd do this instead
=> config to remove $gp, $k0, $k1 for students in cs1521

crates/mipsy_interactive/src/interactive/commands/breakpoint.rs, crates/mipsy_interactive/src/interactive/commands/watchpoint.rs, crates/mipsy_interactive/src/interactive/mod.rs, crates/mipsy_lib/src/compile/breakpoints.rs, crates/mipsy_lib/src/compile/mod.rs, crates/mipsy_web/README.md, crates/mipsy_web/src/components/decompiled.rs, crates/mipsy_web/src/components/registers.rs, crates/mipsy_web/src/pages/main/app.rs, crates/mipsy_web/src/state/update.rs, crates/mipsy_web/src/worker.rs
=> add watchpoints to mipsy_web

crates/mipsy_web/src/worker.rs
i was in the area so decided to fix some clippy
=> fix some clippys

crates/mipsy_parser/src/parser.rs
using this for mipsy_web v2 
currently using my fork of mipsy with these changed until merged
=> add some taggedfile utilties

crates/mipsy_web/src/worker.rs
=> check correct instruction for watchpoints

crates/mipsy_lib/src/error/runtime/mod.rs
`mipsy_lib::error::runtime::try_find_pseudo_expansion_end` would consider uninitialised memory as continuation of a psuedoinstruction, causing a panic.
With this patch, `try_find_pseudo_expansion_end` examines the current state to check if the address is uninitialised. This covers the existing checks for addresses which leave segments, but also now checks for uninitialised memory which is still in bounds for the segment.
Fixes #280.
=> Fix panic from uninitialised memory in error (#280)

crates/mipsy_web/src/state/config.rs
See https://github.com/insou22/mipsy/issues/279
=> Change default mipsy-web register display to decimal (insou22#279)

mips.yaml
=> re-fix the expansion of LA

mips.yaml
HI and LO were in the wrong order.
The quotient should go in LO, and the remainder in HI.
=> Swap HI and LO in desc_short of div instructions
